coverity: fix the RESOURCE_LEAK in peeknpoke
projectceladon/peeknpoke pull request #9
Opened 2024-09-23 03:31 UTC by bhe4

add the close(fd) to fix the RESOURCE_LEAK issue

Tracked-On: OAM-124667

2024-09-24 05:42 UTC, tanujtekriwal requested changes
Also please add "Tests Done: " in the commit message as part of commit message format.

2024-09-24 05:42 UTC, tanujtekriwal commented on mem_dump.c
> +		}
return statement should be inside the if {}

2024-09-24 05:42 UTC, tanujtekriwal commented on mem_dump.c
> +		}
return statement should be inside the if {}

2024-09-25 03:55 UTC, tanujtekriwal commented
> Also please add "Tests Done: " in the commit message as part of commit message format.

Please add this.

2024-09-25 05:30 UTC, bhe4 commented
Added the Tests Done, Please help review.

2024-09-25 05:30 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-09-25 05:30 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-25 05:30 UTC, sysopenci commented
Improper Commit Message
Improper Affects version

2024-09-25 05:34 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-09-25 06:13 UTC, tanujtekriwal approved these changes
LGTM

2024-10-08 05:23 UTC, tanujtekriwal approved these changes
LGTM

2024-10-08 05:30 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-08 10:10 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-09 07:15 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-10-09 11:03 UTC, merged

2024-10-09 11:21 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/157